version: '3.8'

services:
  mongodb:
    build: .
    container_name: wekan-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: wekan
      MONGO_INITDB_ROOT_PASSWORD: wekan
      MONGO_INITDB_DATABASE: wekan
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
