services:
  wekandb:
    image: mongo:6
    container_name: wekan-db
    restart: always
    command: mongod --oplogSize 128
    networks:
      - wekan-tier
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  wekan:
    image: ghcr.io/wekan/wekan:latest
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://localhost:8080
      - PORT=8080
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    depends_on:
      - wekandb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  wekan-tier:
    driver: bridge

volumes:
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local
